from __future__ import annotations

from enum import StrEnum


class Exchange(StrEnum):
    GATE = "gate"


class MarketType(StrEnum):
    USDT_PERPETUAL = "usdt_perpetual"


class ContractType(StrEnum):
    PERPETUAL = "perpetual"


class EligibilityStatus(StrEnum):
    ELIGIBLE = "ELIGIBLE"
    INELIGIBLE = "INELIGIBLE"
    STALE = "STALE"
    UNKNOWN = "UNKNOWN"


class EligibilityReasonCode(StrEnum):
    NOT_EVALUATED = "NOT_EVALUATED"
    PASSES_PHASE2_RULES = "PASSES_PHASE2_RULES"
    INSTRUMENT_INACTIVE = "INSTRUMENT_INACTIVE"
    QUOTE_ASSET_NOT_USDT = "QUOTE_ASSET_NOT_USDT"
    LISTING_AGE_BELOW_THRESHOLD = "LISTING_AGE_BELOW_THRESHOLD"
    SPREAD_ABOVE_THRESHOLD = "SPREAD_ABOVE_THRESHOLD"
    INSUFFICIENT_MARKET_DEPTH = "INSUFFICIENT_MARKET_DEPTH"
    ELIGIBILITY_WINDOW_EXPIRED = "ELIGIBILITY_WINDOW_EXPIRED"
    SYMBOL_NOT_FOUND = "SYMBOL_NOT_FOUND"


class ProposalReasonCode(StrEnum):
    MISSING_REQUIRED_FIELDS = "MISSING_REQUIRED_FIELDS"
    INVALID_INSTRUMENT = "INVALID_INSTRUMENT"
    INSTRUMENT_NOT_ELIGIBLE = "INSTRUMENT_NOT_ELIGIBLE"
    STALE_MARKET_DATA = "STALE_MARKET_DATA"
    PROPOSAL_EXPIRED = "PROPOSAL_EXPIRED"
    CONFIDENCE_TOO_LOW = "CONFIDENCE_TOO_LOW"
    STOP_LOSS_MISSING = "STOP_LOSS_MISSING"
    STOP_LOSS_INVALID = "STOP_LOSS_INVALID"
    RISK_CALCULATION_MISMATCH = "RISK_CALCULATION_MISMATCH"
    POSITION_SIZE_INVALID = "POSITION_SIZE_INVALID"
    ENTRY_SPLIT_INVALID = "ENTRY_SPLIT_INVALID"
    AVERAGING_DOWN_FORBIDDEN = "AVERAGING_DOWN_FORBIDDEN"
    MAX_OPEN_POSITIONS_REACHED = "MAX_OPEN_POSITIONS_REACHED"
    MAX_DAILY_DRAWDOWN_REACHED = "MAX_DAILY_DRAWDOWN_REACHED"
    TOTAL_OPEN_RISK_EXCEEDED = "TOTAL_OPEN_RISK_EXCEEDED"
    RISK_BUDGET_RESERVED = "RISK_BUDGET_RESERVED"
    SYSTEM_BLOCKED = "SYSTEM_BLOCKED"
    SYSTEM_HALTED = "SYSTEM_HALTED"
    STATE_INCONSISTENT = "STATE_INCONSISTENT"


class NoTradeReasonCode(StrEnum):
    NO_CLEAR_STRUCTURE = "NO_CLEAR_STRUCTURE"
    TIMING_UNFAVORABLE = "TIMING_UNFAVORABLE"
    ENTRY_ZONE_MISSED = "ENTRY_ZONE_MISSED"
    RISK_REWARD_INADEQUATE = "RISK_REWARD_INADEQUATE"
    CONFIDENCE_BELOW_THRESHOLD = "CONFIDENCE_BELOW_THRESHOLD"
    POOR_LIQUIDITY = "POOR_LIQUIDITY"
    WIDE_SPREAD = "WIDE_SPREAD"
    INSUFFICIENT_BOOK_DEPTH = "INSUFFICIENT_BOOK_DEPTH"
    STALE_MARKET_DATA = "STALE_MARKET_DATA"
    UNIVERSE_NOT_ELIGIBLE = "UNIVERSE_NOT_ELIGIBLE"
    HOSTILE_REGIME = "HOSTILE_REGIME"
    SIGNAL_STALE = "SIGNAL_STALE"
    CORRELATION_PORTFOLIO_CONFLICT = "CORRELATION_PORTFOLIO_CONFLICT"


class SafetyState(StrEnum):
    NORMAL = "NORMAL"
    WARNING = "WARNING"
    BLOCK_NEW_TRADES = "BLOCK_NEW_TRADES"
    HALTED = "HALTED"
